### ISSUE TITLE
Size-optimized (Huffman) fails in edge cases

### ISSUE THREAD

**Issue by pinnecke** [protolabs/libcarbon#1]
In rare cases, converting a JSON file into a CARBON file fails when using `huffman` encoding. The following example produces such an error:

```
$ cmake . && make carbon-tool
$ echo '{ "_": "_", "topic": "compression" }' > hufferror.json && build/carbon-tool convert --force-overwrite --size-optimized hufferror.carbon hufferror.json
*** ERROR ***   No huffman code table entry found for character
                details: no details
                source.: /Users/marcus/git/ng5/src/carbon/carbon-huffman.c(187)
```

The error occurs in `src/carbon/carbon-huffman.c` when creating the required huffman tree. In particular, it seems that at least one node (having the particular letter contained) is ignored during creation of that tree (same file line 426).

To reproduce and stop, run `carbon-tool` in a debugger with working directory where you stored the `hufferror.json` and with arguments `convert --force-overwrite --size-optimized hufferror.carbon hufferror.json`. When `DEBUG` is enabled, `carbon-tool` should abort when the error is raised.

A minimal example where huffman tree building works, is 
`$ echo '{ "key1": "value1", "key2": "value2", "key3": "value3" }' > huffok.json && build/carbon-tool convert --force-overwrite --size-optimized huffok.carbon huffok.json`

**Comment by pinnecke** [comment]
Please use [fix-issue1-huffman-fails-in-edge-cases](https://github.com/protolabs/libcarbon/tree/fix-issue1-huffman-fails-in-edge-cases) branch for fixing. To turn on some debug information, define `DIAG_HUFFMAN_ENABLE_DEBUG` in `carbon-huffman.c`.

**Comment by mmmohsen** [comment]
The cause of the error for this bug,
regarding this piece of code 

        if(smallest->prev == NULL && small->next == NULL) {
            break;
        }

Not necessary in this case, there are two only candidates.
the quick fix is to ensure that there are two only two candidates by
if what comes after the smallest is actually the small and vice Verca.

**Comment by pinnecke** [comment]
Hey, for both cases (`huffok.json` and `hufferror.json`) everything works now as expected :) Unfortunately, for more complex examples (namely `examples/json/complex.json`, the system now crashes with a segmentation fault. To reproduce this error, try the following:

```
echo '{ "a3": [1.5,2.6,3], "a21": [{ "a": 1 }, { "a": 2, "b": 3, "c": [3] }], "a20": [{ }, { }], "a1": [], "a11": [null], "a12": [null, null], "a13": null, "a14": [true], "a15": [false], "a16": [true, false], "a2": [1,2,3],  "a4": [2.0e9, 2.6, 3],  "a5": ["A", "B", "C"], "a17": [true, false, null], "a18": [true, false, null], "a19": [null, false, true], "a22": [{ "array": [ { "nested-array": [ 1, 2, 3 ] } ] }], "firstName": "John", "lastName": "Smith", "isAlive": true, "age": 27, "float1": 27.0, "float2": 27.08, "float3": -27.08, "float4": -27.08e10, "float4": 27.08e-25, "small": -9223372036854775808, "large":  9223372036854775807, "larger": 9999999999999999999, "largest": 18446744073709551616, "too largest": 18446744073709551616999, "too small": -9223372036854775810, "address": {   "streetAddress": "21 2nd Street",   "city": "New York",   "state": "NY",   "postalCode": "10021-3100",   "nulls": [null, null] }, "phoneNumbers": [   {     "type": "home",     "number": "212 555-1234",     "null": [null],     "nested": [{ "n1": 1, "n2": 2}, {"n1": 3, "n2": 4}]   },   {     "type": "office",     "number": "646 555-4567",     "null": [null, null],     "nested": [{ "a": 1, "b": 2}, {"c": 3, "b": 4}]   },   {     "type": "mobile",     "number": "123 456-7890",     "nested": [{ "a": 1, "b": 2}, {"c": 3, "b": 4}]   } ], "children": [], "spouse": null }' > test.json && build/carbon-tool convert --force-overwrite --size-optimized test.carbon test.json && build/carbon-tool view test.carbon
```

**Comment by pinnecke** [comment]
Nice, works with the current tests :)
